# run it like this OUTPUT="Internal Speakers" open -a SoundOutputChooser.app
# you might need to give it Accessibility control under Preferences -> Security & Privacy

SoundOutputChooser.app: sound_output_chooser.applescript
	osacompile -o $@ $<
